# Generated by Django 5.2.12 on 2026-03-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marine_weather", "0001_load_package"),
    ]

    operations = [
        migrations.RunSQL(
            sql="select __arches_create_resource_model_views(graphid) from graphs where slug <> 'arches_system_settings';",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
